version: '3'

services:
  kafka:
    image: wurstmeister/kafka
    container_name: testKafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: testZookeeper
    ports:
      - "2181:2181"